# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('times', models.IntegerField(default=0)),
                ('query_date', models.DateTimeField(verbose_name='date queried')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Location')),
            ],
        ),
    ]
