# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='id_order',
            field=models.IntegerField(default=0),
        ),
    ]
