# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20160318_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_text', models.CharField(max_length=200)),
                ('times', models.IntegerField(default=0)),
                ('query_date', models.DateTimeField(verbose_name='date queried')),
                ('id_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('id_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Source'),
        ),
    ]
