# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20160318_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='query_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='source',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='times',
        ),
        migrations.RemoveField(
            model_name='source',
            name='pub_date',
        ),
    ]
